### ISSUE TITLE
Problem in ADDTOANY_SHARE_SAVE_FLOATING

### ISSUE THREAD

**Issue by RoccoMarco** [projectestac/wordpress-add-to-any#15]
Additional classes aren't added. Line 685 in add-to-any.php is
$args['kit_additional_classes'] = 'a2a_floating_style a2a_vertical_style';
instead of
$args['kit_additional_classes'] =  trim($args['kit_additional_classes'] . ' a2a_floating_style a2a_vertical_style');
Overwriting user settings 
same on line 707

**Comment by toniginard** [comment]
This plugin is a customized version of the original one: https://wordpress.org/plugins/add-to-any/ Furthermore, we're not using the latest version, so the bug you're reporting might be already fixed. If not, you should report it to the authors of the plugin so it can be fixed in future versions.

Best wishes

**Comment by RoccoMarco** [comment]
Sorry. My bad. I am using the last stable.
